[package]
name = "nmap_helper"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.34", features = ["full", "signal"] }
anyhow = "1.0"
ipnetwork = "0.20"
trust-dns-resolver = "0.23"
futures = "0.3"
indicatif = "0.17"
regex = "1.10"
