name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: nmap_helper
            asset_name: nmap_helper-linux-amd64
            use_cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: nmap_helper.exe
            asset_name: nmap_helper-windows-amd64.exe
            use_cross: false
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: nmap_helper
            asset_name: nmap_helper-macos-amd64
            use_cross: false
          
          # ARM64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_name: nmap_helper
            asset_name: nmap_helper-linux-arm64
            use_cross: true
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: nmap_helper
            asset_name: nmap_helper-macos-arm64
            use_cross: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            binary_name: nmap_helper.exe
            asset_name: nmap_helper-windows-arm64.exe
            use_cross: false

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Cross
        if: matrix.use_cross
        shell: bash
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.use_cross }}" == "true" ]; then
            cross build --release --target ${{ matrix.target }} --verbose
          else
            cargo build --release --target ${{ matrix.target }} --verbose
          fi

      - name: Rename binary
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ matrix.binary_name }} target/${{ matrix.target }}/release/${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.asset_name }}
